src/napari_omaas/__init__.py
src/napari_omaas/_tests/test_widget.py
src/napari_omaas/_widget.py
src/napari_omaas/napari.yaml
src/napari_omaas/utils.py

a number of changes including
- buttons for normalization, invert signal, split channels, segment heart, subtract & remove bkg and pick frames.
- new grouping layout

Rapid user implementation

---

src/napari_omaas/_widget.py
src/napari_omaas/utils.py

add basic logic for image registration using the `optical_flow_ilk` method from skimage after local scaling data transformation. return dataset as type np.unit16.

Motion correction

---

src/napari_omaas/_widget.py
src/napari_omaas/utils.py

Mostly changes related to the temporal filters implementation and reorganizing layout

Adding bare temporal filters logic and functionality

---

.gitignore
setup.cfg
src/napari_omaas/_sample_data.py
src/napari_omaas/napari.yaml

repeat: Create temporal link for sample data

Adding sample data

---

src/napari_omaas/_sample_data.py
src/napari_omaas/_widget.py
src/napari_omaas/utils.py

adding the basics infracstructure for layout and backend to compute APD, etc from singel traces...

Apd functions

---

setup.cfg
src/napari_omaas/_widget.py
src/napari_omaas/utils.py

testing macrokit for recording scripts and easy reproducibility of workflows

basic framework fro recording macro

---

setup.cfg
src/napari_omaas/_widget.py
src/napari_omaas/utils.py
src/test.py

Basic functional replacement of the main canvas for plot profilling traces using simple and more controllable backend with napari_matplotlib replacing napar_TSP

New plot implementation

---

src/napari_omaas/_widget.py

little fixes on APD plot functionality using new plotting backend

New plot implementation on APD

---

README.md

update example image and add new APD example

update example image and add new APD example

---

src/napari_omaas/_widget.py
src/napari_omaas/utils.py

Map analysis

---

setup.cfg
src/napari_omaas/_widget.py
src/napari_omaas/utils.py

this dependency add some bugs due to Pyside, now it's replaced with native qtpy

fix toggle error from qtwidgets dependency

---

src/napari_omaas/_widget.py
src/napari_omaas/utils.py
src/test.py

add histogram visualization support for indivisdual or full images stacks

Histogram plot

---

src/napari_omaas/_widget.py
src/napari_omaas/utils.py

- fix APD bug in APD < ~40 % from peak

Motion correction optimap

---

setup.cfg
src/napari_omaas/__init__.py
src/napari_omaas/_reader.py
src/napari_omaas/_widget.py
src/napari_omaas/napari.yaml
src/napari_omaas/utils.py

this update add support to read .sif image within this plugin avoiding to use the external plugin reader `napari-sif-reader`

Support Reader contribution

---

src/napari_omaas/_reader.py
src/napari_omaas/napari.yaml
src/napari_omaas/utils.py
test_reader_folder.py

- add support to read spool files in a folder

Reader contribution

---

setup.cfg
src/napari_omaas/_widget.py
src/napari_omaas/utils.py
test_APD_ROI.py

this make important changes in the structure of the project:
- unify code structure to handle CPU or GPU to perform some operations
minor changes
- load only explicitaly libraries in GUI
- other changes

Motion_correction_optimap

---

setup.cfg

add PyQt5 for rendering documentation

test debugging napari import error in documentation: 2

---

docs/conf.py
docs/scripts_examples/APD_ROI_analysis_red_only.ipynb
docs/scripts_examples/analysis_dual_illumination.ipynb
docs/scripts_examples/analysis_red_only.ipynb
setup.cfg

remove temporal execution of notebooks

test debugging napari import error in documentation: 3

---

docs/conf.py
docs/scripts_examples/APD_ROI_analysis_red_only.ipynb
docs/scripts_examples/analysis_dual_illumination.ipynb
docs/scripts_examples/analysis_single_illumination.ipynb
docs/scripts_examples/scripts_examples.md
src/napari_omaas/_widget.py

update last example scripts and make them runable from top to bottom

Documentation

---

setup.cfg
src/napari_omaas/_widget.py
src/napari_omaas/utils.py

remove macrokit dependencies and add nested table to visualize processing steps

Remove_macrokit
